### ISSUE TITLE
Maximum Spend should not accept amount less than the Minimum Spend Amount

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#50]
WordPress version: 5.7.1
WooCommerce version: 5.2.1
Area Path: Admin panel --> Gift Cards --> Settings --> GENERAL
Version: 2.0.10
Description: The Maximum Spend field should not accept amount less than the Minimum Spend Amount.
![Screenshot](https://user-images.githubusercontent.com/76723329/114865652-31f90200-9e10-11eb-998c-fd4ac7a4b7aa.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
