### ISSUE TITLE
login here link not working.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#52]
WordPress version: 5.7.1
WooCommerce version: 5.2.1
Area Path: Admin panel --> Gift Cards --> Settings --> GIFT CARD REDEEM
Version: 2.0.10
Description: The login here link not working.
![Screenshot (2)](https://user-images.githubusercontent.com/76723329/114874363-e5b2bf80-9e19-11eb-8ead-32d36ee842cf.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
