### ISSUE TITLE
Default GIFT MESSAGE  character length not coming.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#53]
WordPress version: 5.7.1
WooCommerce version: 5.2.1
Area Path: Store-end --> Gift Card Product
Version: 2.0.10
Description: The Default GIFT MESSAGE  character length not coming.
![Screenshot (4)](https://user-images.githubusercontent.com/76723329/114975629-33730a80-9ea2-11eb-8a26-50ca79ea3f77.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
