### ISSUE TITLE
When we place GC product then it show Internal server error

### ISSUE THREAD

**Issue by cedcoss-pooja** [Makewebbetter/woo-gift-cards-lite#54]
WP version:5.7.1
WC version:5.2.2
Description:When we activate plugin and try to place the order of GC product then it show internal server issue 
![screenshot-localhost_10009-2021 04 16-16_12_58](https://user-images.githubusercontent.com/48902379/115013726-0a1ca380-9ecf-11eb-84f4-473076bec8da.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
working fine

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
