### ISSUE TITLE
Gift card mail is not getting delivered if purchased by Guest User even after order status gets completed by admin.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#55]
WordPress version: 5.7.1
WooCommerce version: 5.2.1
Area Path: Store-end --> Gift Card Product
Version: 2.0.10
Description: The Gift card is not getting delivered if purchased by Guest User even after order status gets completed by admin.

**Comment by pradeepsinghbisht-cedcoss** [comment]
working fine
