### ISSUE TITLE
Logo height and Logo Width fields are accepting negative values.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#56]
WordPress version: 5.7.1
WooCommerce version: 5.2.1
Area Path: Admin panel --> Gift Cards --> EMAIL TEMPLATE
Version: 2.0.10
Description: The Logo height and Logo Width fields are accepting negative values.
![Screenshot (3)](https://user-images.githubusercontent.com/76723329/115102240-3b48b280-9f67-11eb-8cbc-4fdfffec73d3.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
