### ISSUE TITLE
QA issues

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#57]
Version: 2.1.0
Plugin name: Ultimate Gift Cards For WooCommerce

**QA issues:**
die():-
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/woo-gift-cards-lite/admin/class-woocommerce_gift_cards_lite-admin.php line: 1129
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/woo-gift-cards-lite/public/class-woocommerce_gift_cards_lite-public.php line: 1321

.click() - onclick:-
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/woo-gift-cards-lite/admin/js/woocommerce_gift_cards_lite-admin.js line: 50, 62, 68, 95, 115, 220, 225

.submit() - onsubmit:-
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/woo-gift-cards-lite/admin/js/woocommerce_gift_cards_lite-admin.js line: 283
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/woo-gift-cards-lite/public/js/woocommerce_gift_cards_lite-public.js line: 238

CURL used:-
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/woo-gift-cards-lite/includes/class-makewebbetter-onboarding-helper.php line: 884, 914

Plugin version:-
/home/cedcoss/Local Sites/mwb-testing/app/public/wp-content/plugins/woo-gift-cards-lite/woocommerce_gift_cards_lite.php line: 52

phpcs issues: [woo-gift-cards-lite.docx](https://github.com/Makewebbetter/woo-gift-cards-lite/files/6364028/woo-gift-cards-lite.docx)

**Comment by pradeepsinghbisht-cedcoss** [comment]
resolved

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
QA issues:
[woo-gift-cards-lite.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/6856376/woo-gift-cards-lite.txt)

phpcs issues:
[woo-gift-cards-lite.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/6856417/woo-gift-cards-lite.txt)

**Comment by pradeepsinghbisht-cedcoss** [comment]
Done

**Comment by ChiragGupta-CEDCOSS** [comment]
Still pending phpcs issues:
[woo-gift-cards-lite.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/6868674/woo-gift-cards-lite.txt)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Ultimate Gift Cards For WooCommerce
Version: 2.2.1
phpcs issues:
[woo-gift-cards-lite.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7445956/woo-gift-cards-lite.txt)
[woo-gift-cards-lite-extended.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7445957/woo-gift-cards-lite-extended.txt)

QA issues:
[woo-gift-cards-lite QA issues.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7445958/woo-gift-cards-lite.QA.issues.txt)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixable issues are fixed
[woo-gift-cards-lite (1).txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7451858/woo-gift-cards-lite.1.txt)
[woo-gift-cards-lite-extended.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7451859/woo-gift-cards-lite-extended.txt)
[woo-gift-cards-lite.QA.issues.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7451860/woo-gift-cards-lite.QA.issues.txt)

**Comment by ChiragGupta-CEDCOSS** [comment]
Fine for now.

**Comment by ChiragGupta-CEDCOSS** [comment]
phpcs issues:
[woo-gift-cards-lite.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7600426/woo-gift-cards-lite.txt)

QA issues:
[woo-gift-cards-lite.QA.issues.txt](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7600423/woo-gift-cards-lite.QA.issues.txt)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed
