### ISSUE TITLE
giftcard prefix setting is not working

### ISSUE THREAD

**Issue by cedcoss-pooja** [Makewebbetter/woo-gift-cards-lite#58]
![screenshot-localhost_10019-2021 04 28-14_20_47](https://user-images.githubusercontent.com/48902379/116375619-15f05a00-a82d-11eb-92e8-5edbfc418ee5.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
resolved

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
