### ISSUE TITLE
Grammatical issues

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#61]
Version: 2.1.0
Plugin name: Ultimate Gift Cards For WooCommerce

**Grammatical issues:**
#: admin/class-woocommerce-gift-cards-lite-admin.php:362
msgid "Enter price using seperator |. Ex : (10 | 20)"
msgstr ""
--> "Enter price using separator |. Ex : (10 | 20)"

#: admin/partials/templates/mwb_wgm_settings/mwb-wgm-general-settings-array.php:65
msgid ""
"Enter gift card coupon length excluding the prefix.(Minimum length is set to "
"5)"
msgstr ""
--> "Enter gift card coupon length excluding the prefix. (Minimum length is set to "

#: admin/partials/templates/mwb_wgm_settings/mwb-wgm-general-settings-array.php:82
msgid ""
"Enter number of days after purchased Giftcard is expired. Keep value \"1\" "
"for one day expiry when order is completed. Keep value \"0\" for no expiry."
msgstr ""
--> "for one-day expiry when order is completed. Keep value \"0\" for no expiry."

#: admin/partials/templates/mwb_wgm_settings/mwb-wgm-mail-template-settings-array.php:40
msgid "Upload the image which is used as logo on your Email Template."
msgstr ""
--> "Upload the image which is used as a logo on your Email Template."

#: admin/partials/templates/mwb_wgm_settings/mwb-wgm-mail-template-settings-array.php:64
msgid ""
"Upload image which is used as a default Event/Occasion in Email Template."
msgstr ""
--> "Upload an image which is used as a default Event/Occasion in Email Template."

#: admin/partials/templates/redeem-giftcard-settings.php:278
msgid ""
"Click on Open Shop button and login using the credentials provided in the "
"received email"
msgstr ""
--> "Click on the Open Shop button and log in using the credentials provided in the "

#: admin/partials/templates/redeem-giftcard-settings.php:282
msgid "To use the redeem link on the web store follow the steps below"
msgstr ""
--> "To use the redeem link on the web-store follow the steps below"

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.

**Comment by ChiragGupta-CEDCOSS** [comment]
Version: 2.2.1
Plugin name: Ultimate Gift Cards For WooCommerce
- Getting error while updating language files. Also, link is coming in language files.
![Screenshot from 2021-11-01 19-01-03](https://user-images.githubusercontent.com/76723329/139680883-0c31fa73-670a-4085-827a-611f0fadba6f.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
link issue resolved

**Comment by ChiragGupta-CEDCOSS** [comment]
Fine for now.
