### ISSUE TITLE
PDF feature is not working in Imported Gift Card products.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#63]
WordPress version: 5.7.1
WooCommerce version: 5.2.2
Area Path: Shop --> Giftcard-Import
Version: 2.0.10
Description: PDF feature is not working in Imported Gift Card products.
![Screenshot (82)](https://user-images.githubusercontent.com/76723329/116882464-1aa87a00-ac42-11eb-8ee6-f6ac96870a30.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Working fine.
