### ISSUE TITLE
Imported Gift Card product orders are not getting listed in GC Reports.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#64]
WordPress version: 5.7.1
WooCommerce version: 5.2.2
Area Path: Shop --> Giftcard-Import
Version: 2.0.10
Description: Imported Gift Card product orders are not getting listed in GC Reports.
![Screenshot (83)](https://user-images.githubusercontent.com/76723329/116884343-43ca0a00-ac44-11eb-8d28-1a1f8a86d26a.png)
![Screenshot (84)](https://user-images.githubusercontent.com/76723329/116884360-475d9100-ac44-11eb-8696-5e890b774f81.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
