### ISSUE TITLE
Send Today button is not working fine in Imported Gift Card orders.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#65]
WordPress version: 5.7.1
WooCommerce version: 5.2.2
Area Path: Shop --> Giftcard-Import
Version: 2.0.10
Description: Send Today button is not working fine in Imported Gift Card orders.
![Screenshot (85)](https://user-images.githubusercontent.com/76723329/116887592-1b440f00-ac48-11eb-8165-f411e79e6d8a.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
