### ISSUE TITLE
Resend Giftcard Email is not working fine in Imported Gift Card orders.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#66]
WordPress version: 5.7.1
WooCommerce version: 5.2.2
Area Path: Shop --> Giftcard-Import
Version: 2.0.10
Description: Resend Giftcard Email is not working fine in Imported Gift Card orders.
![Screenshot (86)](https://user-images.githubusercontent.com/76723329/116888796-7fb39e00-ac49-11eb-83c6-4be61c2a4272.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Working Fine.
