### ISSUE TITLE
Plugin version should be updated.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#68]
WordPress version: 5.7.1
WooCommerce version: 5.2.1
Area Path: Admin panel --> Plugins
Version: 2.1.3
Description: Plugin version should be updated to 2.1.3 
![Screenshot (79)](https://user-images.githubusercontent.com/76723329/124703822-9d82d500-df10-11eb-9f2a-9dbf771cc974.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
