### ISSUE TITLE
Add New gift card template option is available on multisite.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#71]
WordPress version: 5.8.1
WooCommerce version: 5.7.0
Compatibility: Multisite
Area Path: Admin panel --> Gift Cards --> Add New
Version: 2.1.4
Description: Add New gift card template option is available on multisite.
![Screenshot - 2021-09-22T173603 220](https://user-images.githubusercontent.com/76723329/134340978-a51ce1e2-9ff2-487a-90ba-77c3b0456fa5.png)
![Plugins ‹ Mult](https://user-images.githubusercontent.com/76723329/134341027-f3b70f4b-e183-47e4-abf5-fbf83505d759.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
