### ISSUE TITLE
Button to dismiss the notice is not working.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#72]
WordPress version: 5.8.1
WooCommerce version: 5.7.0
Compatibility: Multisite
Area Path: Admin panel --> Gift Cards --> Settings
Version: 2.1.4
Description: The button to dismiss notice is not working.
![Screenshot - 2021-09-22T174344 851](https://user-images.githubusercontent.com/76723329/134341538-b2a7a5e2-cc48-45f6-b1d4-cdd5a9b28fa1.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
