### ISSUE TITLE
Error message is not coming after deactivating WooCommerce.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#73]
WordPress version: 5.8.1
WooCommerce version: 5.7.0
Compatibility: Multisite
Area Path: Admin panel-> Plugins
Version: 2.1.4
Description: The error message is not coming after deactivating WooCommerce.
![Screenshot - 2021-09-22T175405 697](https://user-images.githubusercontent.com/76723329/134343000-340cf16c-8b4b-4474-8b82-9ce06983a785.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
done

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
