### ISSUE TITLE
GC coupon amount is not getting converted with currency.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#74]
WordPress version: 5.8.1
WooCommerce version: 5.7.1
Compatibility: MWB Multi Currency Switcher For WooCommerce/ Multisite
Area Path: Cart
Version: 2.1.4
Description: GC coupon amount is not getting converted with currency.
![Screenshot - 2021-09-24T184335 713](https://user-images.githubusercontent.com/76723329/134680675-95b400d8-4dfd-4624-b65a-8e06dfda92b7.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
working fine

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
