### ISSUE TITLE
Validation error is coming in other currency.

### ISSUE THREAD

**Issue by ChiragGupta-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#75]
WordPress version: 5.8.1
WooCommerce version: 5.7.1
Compatibility: MWB Multi Currency Switcher For WooCommerce
Area Path: Cart
Version: 2.1.4
Description: Validation error is coming in other currency while applying GC coupon at cart.
![Screenshot - 2021-09-24T185647 072](https://user-images.githubusercontent.com/76723329/134682501-7f9d79bb-8821-4de2-98e2-0411eb495cec.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
this issue is coming from MWB Multi Currency Switcher For WooCommerce plugin

**Comment by ChiragGupta-CEDCOSS** [comment]
Implemented fine.
