### ISSUE TITLE
QA/PHPcs Issue 

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#76]
DOC;
https://docs.google.com/document/d/1x2NHEUs0kiZZb0xZydUzJz2CpWOg6sLQMJoD0_1ZVcg/edit?usp=sharing

File:
[PHPcs.xml.zip](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7258844/PHPcs.xml.zip)
[woo-gift-cards-lite.zip](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7258847/woo-gift-cards-lite.zip)

**Comment by pradeepsinghbisht-cedcoss** [comment]
fixed
