### ISSUE TITLE
QA/PHPcs Issues

### ISSUE THREAD

**Issue by Sukirti-CEDCOSS** [Makewebbetter/woo-gift-cards-lite#81]
DOC:
https://docs.google.com/document/d/1HgrUfRwv6LbbNrFHbT7858T13vz1A-mYWgyL9b41dA8/edit?usp=sharing

 File:
[woo-gift-cards-lite.zip](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7950736/woo-gift-cards-lite.zip)
[ORG.zip](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7950740/ORG.zip)
[giftware.zip](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7950741/giftware.zip)
[PRO.zip](https://github.com/Makewebbetter/woo-gift-cards-lite/files/7950745/PRO.zip)

Language Issue:
Some strings are not translated
![image](https://user-images.githubusercontent.com/85384857/151368407-93d20d4b-733b-4f56-8161-69075f9f7cd1.png)

**Comment by pradeepsinghbisht-cedcoss** [comment]
Done

**Comment by Sukirti-CEDCOSS** [comment]
verified
